// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fast_accel_fast_accel,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6751,HLS_SYN_LUT=9121,HLS_VERSION=2022_2}" *)

module fast_accel (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] img_in;
wire   [31:0] threshold;
wire   [63:0] img_out;
wire   [31:0] rows;
wire   [31:0] cols;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state5;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state12;
reg   [31:0] cols_read_reg_315;
reg  signed [31:0] rows_read_reg_328;
reg   [63:0] img_out_read_reg_335;
reg   [31:0] threshold_read_reg_340;
reg   [63:0] img_in_read_reg_346;
reg   [61:0] trunc_ln_reg_351;
wire   [31:0] grp_fu_159_p2;
reg   [31:0] mul_reg_357;
wire    ap_CS_fsm_state3;
wire   [30:0] trunc_ln28_fu_163_p1;
reg   [30:0] trunc_ln28_reg_363;
wire   [30:0] empty_fu_172_p3;
reg   [30:0] empty_reg_368;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln34_fu_193_p2;
reg   [31:0] add_ln34_reg_378;
wire    ap_CS_fsm_state10;
wire   [31:0] select_ln34_fu_224_p3;
reg   [31:0] select_ln34_reg_383;
wire   [31:0] select_ln34_1_fu_253_p3;
reg   [31:0] select_ln34_1_reg_388;
wire    ap_CS_fsm_state11;
wire   [63:0] grp_fu_267_p2;
reg   [63:0] bound_reg_403;
wire   [31:0] sub38_fu_273_p2;
reg   [31:0] sub38_reg_408;
wire    ap_CS_fsm_state13;
wire   [31:0] mul31_fu_284_p2;
reg   [31:0] mul31_reg_413;
wire   [31:0] mul31_2_fu_290_p2;
reg   [31:0] mul31_2_reg_418;
wire   [31:0] empty_25_fu_296_p2;
reg   [31:0] empty_25_reg_423;
wire   [31:0] mul62_5_fu_302_p2;
reg   [31:0] mul62_5_reg_428;
wire   [31:0] mul62_6_fu_308_p2;
reg   [31:0] mul62_6_reg_433;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_done;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_idle;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_ready;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWVALID;
wire   [63:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWADDR;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWLEN;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWSIZE;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWBURST;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWLOCK;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWCACHE;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWPROT;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWQOS;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWREGION;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WVALID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WDATA;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WSTRB;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WLAST;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WID;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARVALID;
wire   [63:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARADDR;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARLEN;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARSIZE;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARBURST;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARLOCK;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARCACHE;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARPROT;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARQOS;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARREGION;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_RREADY;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_BREADY;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_idle;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_ready;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWVALID;
wire   [63:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWADDR;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWLEN;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWSIZE;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWBURST;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWLOCK;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWCACHE;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWPROT;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWQOS;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWREGION;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WVALID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WDATA;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WSTRB;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WLAST;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WID;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARVALID;
wire   [63:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARADDR;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARID;
wire   [31:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARLEN;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARSIZE;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARBURST;
wire   [1:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARLOCK;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARCACHE;
wire   [2:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARPROT;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARQOS;
wire   [3:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARREGION;
wire   [0:0] grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARUSER;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_RREADY;
wire    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_BREADY;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg   [31:0] gmem_WDATA;
reg   [3:0] gmem_WSTRB;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg;
wire    ap_CS_fsm_state14;
wire  signed [63:0] sext_ln28_fu_179_p1;
wire   [31:0] zext_ln28_fu_189_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln28_fu_167_p2;
wire   [31:0] add_ln34_1_fu_198_p2;
wire   [29:0] tmp_fu_203_p4;
wire   [0:0] icmp_fu_213_p2;
wire   [31:0] add_ln34_2_fu_219_p2;
wire   [29:0] tmp_1_fu_232_p4;
wire   [0:0] icmp34_fu_242_p2;
wire   [31:0] add_ln34_3_fu_248_p2;
wire   [31:0] grp_fu_267_p0;
wire   [31:0] grp_fu_267_p1;
wire   [31:0] empty_24_fu_279_p2;
reg    grp_fu_267_ce;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire   [63:0] grp_fu_267_p00;
wire   [63:0] grp_fu_267_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg = 1'b0;
#0 grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg = 1'b0;
end

fast_accel_fast_accel_Pipeline_VITIS_LOOP_28_1 grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start),
    .ap_done(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_done),
    .ap_idle(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_idle),
    .ap_ready(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_ready),
    .m_axi_gmem_AWVALID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln28(trunc_ln_reg_351),
    .mul(mul_reg_357)
);

fast_accel_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3 grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start),
    .ap_done(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done),
    .ap_idle(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_idle),
    .ap_ready(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_ready),
    .m_axi_gmem_AWVALID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .add_ln34(add_ln34_reg_378),
    .bound(bound_reg_403),
    .sext_ln34(cols_read_reg_315),
    .img_in(img_in_read_reg_346),
    .sext_ln45(mul31_reg_413),
    .threshold(threshold_read_reg_340),
    .sub38(sub38_reg_408),
    .sext_ln45_3(mul31_2_reg_418),
    .sext_ln57_1(empty_25_reg_423),
    .sext_ln57_3(mul62_5_reg_428),
    .sext_ln57_5(mul62_6_reg_433),
    .img_out(img_out_read_reg_335)
);

fast_accel_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .threshold(threshold),
    .rows(rows),
    .cols(cols),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fast_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_in(img_in),
    .img_out(img_out)
);

fast_accel_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARADDR),
    .I_ARLEN(grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWLEN(gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(gmem_WDATA),
    .I_WSTRB(gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

fast_accel_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U19(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(cols_read_reg_315),
    .din1(rows_read_reg_328),
    .ce(1'b1),
    .dout(grp_fu_159_p2)
);

fast_accel_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U20(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_267_p0),
    .din1(grp_fu_267_p1),
    .ce(grp_fu_267_ce),
    .dout(grp_fu_267_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_ready == 1'b1)) begin
            grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg <= 1'b1;
        end else if ((grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_ready == 1'b1)) begin
            grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln34_reg_378 <= add_ln34_fu_193_p2;
        select_ln34_1_reg_388 <= select_ln34_1_fu_253_p3;
        select_ln34_reg_383 <= select_ln34_fu_224_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bound_reg_403 <= grp_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cols_read_reg_315 <= cols;
        img_in_read_reg_346 <= img_in;
        img_out_read_reg_335 <= img_out;
        rows_read_reg_328 <= rows;
        threshold_read_reg_340 <= threshold;
        trunc_ln_reg_351 <= {{img_out[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        empty_25_reg_423[31 : 1] <= empty_25_fu_296_p2[31 : 1];
        mul31_2_reg_418 <= mul31_2_fu_290_p2;
        mul31_reg_413 <= mul31_fu_284_p2;
        mul62_5_reg_428 <= mul62_5_fu_302_p2;
        mul62_6_reg_433[31 : 1] <= mul62_6_fu_308_p2[31 : 1];
        sub38_reg_408 <= sub38_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_reg_368 <= empty_fu_172_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_reg_357 <= grp_fu_159_p2;
        trunc_ln28_reg_363 <= trunc_ln28_fu_163_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_ARVALID = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_AWADDR = sext_ln28_fu_179_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_AWADDR = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWADDR = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_AWLEN = zext_ln28_fu_189_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_AWLEN = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWLEN = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_AWVALID = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_AWVALID = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_BREADY = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_BREADY = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_RREADY = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_WDATA = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_WDATA = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WDATA;
    end else begin
        gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_WSTRB = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_WSTRB = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WSTRB;
    end else begin
        gmem_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_WVALID = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_m_axi_gmem_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        gmem_WVALID = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_fu_267_ce = 1'b1;
    end else begin
        grp_fu_267_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_1_fu_198_p2 = ($signed(rows_read_reg_328) + $signed(32'd4294967293));

assign add_ln34_2_fu_219_p2 = ($signed(rows_read_reg_328) + $signed(32'd4294967290));

assign add_ln34_3_fu_248_p2 = ($signed(cols_read_reg_315) + $signed(32'd4294967290));

assign add_ln34_fu_193_p2 = ($signed(cols_read_reg_315) + $signed(32'd4294967293));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_24_fu_279_p2 = cols_read_reg_315 << 32'd2;

assign empty_25_fu_296_p2 = cols_read_reg_315 << 32'd1;

assign empty_fu_172_p3 = ((icmp_ln28_fu_167_p2[0:0] == 1'b1) ? trunc_ln28_reg_363 : 31'd0);

assign grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start = grp_fast_accel_Pipeline_VITIS_LOOP_28_1_fu_123_ap_start_reg;

assign grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start = grp_fast_accel_Pipeline_VITIS_LOOP_34_2_VITIS_LOOP_35_3_fu_131_ap_start_reg;

assign grp_fu_267_p0 = grp_fu_267_p00;

assign grp_fu_267_p00 = select_ln34_reg_383;

assign grp_fu_267_p1 = grp_fu_267_p10;

assign grp_fu_267_p10 = select_ln34_1_reg_388;

assign icmp34_fu_242_p2 = (($signed(tmp_1_fu_232_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_213_p2 = (($signed(tmp_fu_203_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_167_p2 = (($signed(mul_reg_357) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign mul31_2_fu_290_p2 = (cols_read_reg_315 - empty_24_fu_279_p2);

assign mul31_fu_284_p2 = (empty_24_fu_279_p2 - cols_read_reg_315);

assign mul62_5_fu_302_p2 = (32'd0 - cols_read_reg_315);

assign mul62_6_fu_308_p2 = (32'd0 - empty_25_fu_296_p2);

assign select_ln34_1_fu_253_p3 = ((icmp34_fu_242_p2[0:0] == 1'b1) ? add_ln34_3_fu_248_p2 : 32'd0);

assign select_ln34_fu_224_p3 = ((icmp_fu_213_p2[0:0] == 1'b1) ? add_ln34_2_fu_219_p2 : 32'd0);

assign sext_ln28_fu_179_p1 = $signed(trunc_ln_reg_351);

assign sub38_fu_273_p2 = (32'd0 - threshold_read_reg_340);

assign tmp_1_fu_232_p4 = {{add_ln34_fu_193_p2[31:2]}};

assign tmp_fu_203_p4 = {{add_ln34_1_fu_198_p2[31:2]}};

assign trunc_ln28_fu_163_p1 = grp_fu_159_p2[30:0];

assign zext_ln28_fu_189_p1 = empty_reg_368;

always @ (posedge ap_clk) begin
    empty_25_reg_423[0] <= 1'b0;
    mul62_6_reg_433[0] <= 1'b0;
end

endmodule //fast_accel
